include:
  - path: ../.extras/compose/backend/compose.yml

version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: "rolemapper"
        NEXT_PUBLIC_KEYCLOAK_CLIENT_SECRET: "zomzt73VuP6LTUpPpZf5pghlv8exNCtB"
        NEXT_PUBLIC_KEYCLOAK_ISSUER: "http://keycloak:8080/realms/flowcraft"
        NEXT_PUBLIC_BACKEND_SERVER_URL: "https://backend:3000/graphql"
        NEXT_PUBLIC_LOG_LEVEL: "debug"
        NEXT_PUBLIC_NODE_ENV: "development"
        NEXT_PUBLIC_PINO_PRETTY: "true"
        NEXT_PUBLIC_LOG_DIR: "logs"
        NEXTAUTH_SECRET: "secret"
        NODE_TLS_REJECT_UNAUTHORIZED: "0"
    env_file: ../.extras/compose/frontend/.env
    ports:
      - published: 4000
        target: 4000
    depends_on:
      backend:
        condition: service_started
    volumes:
      - type: bind
        source: ./logs
        target: /opt/app/logs
        read_only: false
      - type: bind
        source: ../.volumes/keys/certificate.crt
        target: /opt/.volumes/keys/certificate.crt
        read_only: true
      - type: bind
        source: ../.volumes/keys/key.pem
        target: /opt/.volumes/keys/key.pem
        read_only: true
    container_name: rolemapper-frontend
    hostname: frontend
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G
