'use client';

import CssBaseline from '@mui/material/CssBaseline';
import { SessionProvider } from 'next-auth/react';
import localFont from 'next/font/local';
import React from 'react';
import Navigation from '../components/Navigation';
import ThemeProviderWrapper from '../theme/ThemeProviderWrapper';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProviderWrapper>
          <SessionProvider>
            {/* <ThemeProvider theme={theme}> */}
            <CssBaseline />
            <Navigation />
            {children}
            {/* </ThemeProvider> */}
          </SessionProvider>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
