/**
 * @file page.tsx
 * Server-Komponente für die Rollenverwaltung.
 * Diese Komponente dient als Wrapper, der die Client-Komponente `ClientRolesPage` rendert.
 *
 * @module RolesPage
 */

import { Metadata } from 'next';
import ClientRolesPage from './rolesPage';

/**
 * Metadata für die Rollen-Page.
 * Wird von Next.js genutzt, um Titel und Beschreibung der Seite festzulegen.
 *
 * @constant
 * @type {Metadata}
 * @property {string} title - Der Titel der Seite.
 * @property {string} description - Beschreibung der Seite.
 */

export const metadata: Metadata = {
  title: 'Rollen',
  description: 'Generated by create next app',
};

/**
 * Server-Komponente zur Datenabfrage und Weiterleitung.
 *
 * Diese Komponente wird serverseitig gerendert und dient als Wrapper für die
 * clientseitige `ClientRolesPage`. Die Struktur ermöglicht die Nutzung
 * von serverseitigen und clientseitigen Rendering-Ansätzen.
 *
 * @async
 * @function
 * @returns {JSX.Element} Die gerenderte Client-Komponente.
 *
 * @example
 * Aufruf in Next.js:
 * export default async function App() {
 *   return <RolesPage />;
 * }
 */
export default async function RolesPage() {
  return <ClientRolesPage />;
}
