// page.tsx (Server-Komponente)

import { Metadata } from 'next';
import ClientRolesPage from './rolesPage';

export const metadata: Metadata = {
  title: 'Rollen',
  description: 'Generated by create next app',
};

// Server-Komponente zur Datenabfrage
export default async function RolesPage() {
  return <ClientRolesPage />;
}
