import ArrowLeftIcon from "@heroicons/react/24/outline/ArrowLeftIcon";
import { LoginForm } from "./LoginForm";
import Link from "next/dist/client/link.js";

export const metadata = {
  title: 'Login',
  description: 'Generated by Next.js',
}

export default function Login() {
    return (
        <div className="d-flex align-items-center justify-content-center" style={{ height: 750 }}>
        <div className="position-relative w-50 mw-md overflow-hidden rounded-2xl border border-light shadow-lg rounded-4 position-relative">
          <Link href={"/"}>
            <ArrowLeftIcon className="position-absolute top-0 start-0" style={{ width: "2rem" }} />
          </Link>
                <div className="  d-flex flex-column align-items-center justify-content-center gap-3 border-bottom border-secondary px-4 py-6 pt-8 text-center sm:px-4">
                    <h3 className="fs-4 fw-semibold">Sign In</h3>
                    <p className="fs-6 text-muted">Use your email and password to sign in</p>
                </div>
                <LoginForm />
            </div>
        </div>
    );
}
