import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Organisationseinheiten',
  description: 'Generated by create next app',
};

export default function OrganisationeinheitenLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body>{children}</body>
    </html>
  );
}
