services:
  keycloak:
    image: keycloak/keycloak:latest
    #depends_on: [db]
    ports:
      - published: 8880
        target: 8080
      - published: 8843
        target: 8443
    volumes:
      - type: bind
        source: ../../../volumes/keycloak
        target: /opt/keycloak/data
      - type: bind
        source: ../../../volumes/keys/key.pem
        target: /opt/keycloak/conf/key.pem
        read_only: true
      - type: bind
        source: ../../../volumes/keys/certificate.crt
        target: /opt/keycloak/conf/certificate.crt
        read_only: true
    env_file: .env
    hostname: keycloak
    container_name: keycloak
    user: keycloak:1000
    entrypoint:
      - '/opt/keycloak/bin/kc.sh'
      - 'start-dev'
      # - '--https-key-store-file=/opt/keycloak/conf/certificate.crt'
      # - '--https-key-store-password=changeit'

    cap_drop: [ALL]
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '2.0'
          memory: 2G
