#$env:ACTIVE_PROFILE = "neo4j"
NEO4J_USER_NAME:  neo4j
NEO4J_USER_PASSWORT: etKQol0amoLZfuvpvycM4Wrw_RLnL0NMUKOsRy-1jGM

spring:
  neo4j:
    uri: neo4j+s://96568970.databases.neo4j.io
    authentication:
      username: ${NEO4J_USER_NAME}
      password: ${NEO4J_USER_PASSWORT}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.mongodb.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongodb.MongoReactiveDataAutoConfiguration

  config:
    activate:
      on-profile: neo4j


