# ==============================================================================
# N o d e
# ==============================================================================
node:
  port: 3000

# ==============================================================================
# K e y c l o a k
# ==============================================================================
keycloak:
  authServerUrl: http://localhost:18080/auth
  # realm: flowcraft
  # clientId: rolemapper
  #tokenValidation: online

  realm: camunda-platform
  clientId: camunda-identity

# ==============================================================================
# L o g g i n g
# ==============================================================================
log:
  level: debug
  #dir: ./logs
  pretty: true

# ==============================================================================
# H e a l t h
# ==============================================================================
health:
  prettyPrint: true

# ==============================================================================
# M a i l s e r v e r
# ==============================================================================
mail:
  activated: false
  host: localhost
  port: 8025
  log: false

# ==============================================================================
# T e s t s
# ==============================================================================
#test:
#  startDbServer: false


# ==============================================================================
# Z E E B E
# ==============================================================================
zeebe:
  url: localhost:26500
  enable: true
