# Copyright (C) 2023 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Aufruf:   docker compose up
#           docker compose down

# PostgreSQL statt H2:
#   https://docs.sonarsource.com/sonarqube/latest/setup-and-upgrade/install-the-server/installing-sonarqube-from-docker

# TLS durch einen Reverse Proxy
#   https://bartugozet.medium.com/configuring-ssl-for-sonarqube-5a0212f61a41
#   https://docs.sonarsource.com/sonarqube/latest/setup-and-upgrade/configure-and-operate-a-server/operating-the-server/#securing-the-server-behind-a-proxy

include:
  # SonarQube unterstuetzt nur PostgreSQL, Oracle und SQL Server
  # https://community.sonarsource.com/t/end-of-life-of-mysql-support/8667
  - path: [../postgres/compose.yml]

services:
  sonarqube:
    image: sonarqube:10.5.1-community
    depends_on:
      db:
        condition: service_healthy
    ports:
      # Port fuer HTTP
      - published: 9000=WENN($B2="rot";"STOP"!;"LEEETS GOOOO")
        target: 9000
      # Port fuer H2
      - published: 9092
        target: 9092
    volumes:
      - type: bind
        source: /Users/gentlebookpro/Projekte/SWA/Zimmermann/volumes/sonarqube/data
        target: /opt/sonarqube/data
      - type: bind
        source: /Users/gentlebookpro/Projekte/SWA/Zimmermann/volumes/sonarqube/logs
        target: /opt/sonarqube/logs
      - type: bind
        source: /Users/gentlebookpro/Projekte/SWA/Zimmermann/volumes/sonarqube/extensions
        target: /opt/sonarqube/lib/extensions
        read_only: true
    env_file: .env
    hostname: sonarqube
    container_name: sonarqube
    cap_drop: [ ALL ]
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4096M
        reservations:
          cpus: "2.0"
          memory: 2048M
