name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Nur für Versionstags (z.B. v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend # Globale Einstellung für alle Schritte in diesem Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Compile TypeScript
        run: npx tsc

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist

  analyze:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run eslint

      - name: Run security audit
        run: npm audit --omit=dev

      - name: Generate documentation
        run: npm run typedoc

  package:
    runs-on: ubuntu-latest
    needs: [build, analyze]
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Package application
        run: zip -r dist.zip dist

      - name: Upload packaged artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packaged-artifacts
          path: dist.zip

  docker:
    runs-on: ubuntu-latest
    needs: package
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download packaged artifacts
        uses: actions/download-artifact@v4
        with:
          name: packaged-artifacts

      - name: Build Docker image
        run: |
          docker build -t flowcraft/role-mapper:2024.12.1 .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push flowcraft/role-mapper:2024.12.1
