name: CI/CD Pipeline Backend

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
      - CD/CI---Security
    tags:
      - 'v*'  # Nur für Versionstags (z.B. v1.0.0)
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print ref name
        run: echo "This workflow was triggered by ${{ github.ref_name }}"

      - name: Print actor
        run: echo "The actor is ${{ github.actor }}"

      - name: Print tag
        run: echo "The actor is ${{ github.ref_name }}"

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Compile TypeScript
        run: npx tsc

      # - name: Upload dist folder
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: dist-${{ matrix.node-version }}
      #     path: backend/dist
      #     retention-days: 1

      - name: save dist folder
        run: |
         echo "DIST_PATH=$(pwd)/dist" >> $GITHUB_ENV


  # analyze:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: backend
  #   needs: build
  #   strategy:
  #     matrix:
  #       node-version: [22.x]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ matrix.node-version }}

  #     - name: gib dist pfad
  #       run: ls $DIST_PATH

  #     - name: Restore Node.js modules from cache
  #       uses: actions/cache@v4
  #       with:
  #         path: backend/node_modules
  #         key: ${{ runner.os }}-node-modules-${{ hashFiles('backend/package-lock.json') }}

  #     - name: Lint code
  #       run: npm run eslint

  #     - name: Security audit
  #       run: npm audit --omit=dev

  #     - name: Generate documentation (TypeDoc)
  #       run: npm run typedoc

  #     - name: Deploy to GitHub Pages
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  #         publish_dir: ./docs/backend

  #     - name: Comment Lint and Audit Results
  #       if: github.event_name == 'pull_request'
  #       uses: actions/github-script@v7
  #       with:
  #         script: |
  #           github.rest.issues.createComment({
  #             issue_number: context.issue.number,
  #             owner: context.repo.owner,
  #             repo: context.repo.repo,
  #             body: 'Analysis Complete: Code Lint and Audit Passed ✅',
  #           })

  package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    needs: [build]
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download dist folder
        uses: actions/download-artifact@v4
        with:
          name: dist-${{ matrix.node-version }}
          path: backend/dist

      - name: Package distribution
        run: zip -r dist.zip ${{ env.DIST_PATH }}

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: dist-package-${{ matrix.node-version }}
          path: backend/dist.zip

  docker:
    defaults:
      run:
        working-directory: backend
    runs-on: ubuntu-latest
    needs: package
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore Node.js modules from cache
        uses: actions/cache@v4
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('backend/package-lock.json') }}

      - name: Download dist folder
        uses: actions/download-artifact@v4
        with:
          name: dist-package-${{ matrix.node-version }}
          path: ./backend

      - name: unzip dist folder
        run: unzip dist.zip -d $DIST_PATH

      - name: Create .env file
        run: |
          echo "NODE_ENV=development" >> .env
          echo "CLIENT_SECRET=${{ secrets.KEYCLOAK_CLIENT_SECRET }}" >> .env
          echo "SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}" >> .env
          echo "SNYK_TOKEN=${{ secrets.SNYK_TOKEN }}" >> .env

      - name: Build Docker image
        run: |
          docker build \
            --build-arg NODE_ENV=development \
            --build-arg CLIENT_SECRET=${{ secrets.KEYCLOAK_CLIENT_SECRET }} \
            --build-arg SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
            --build-arg SNYK_TOKEN=${{ secrets.SNYK_TOKEN }} \
            -t flowcraft/role-mapper:2024.12.1 .

      - name: Clean up .env file
        run: rm .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to registry
        run: |
          docker tag flowcraft/role-mapper:2024.12.1 calebscript/role-mapper:2024.12.1
          docker push calebscript/role-mapper:2024.12.1
