name: Security Pipeline
on:
  push:
    branches:
      - CD/CI---Security
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  security:
    name: Security Scans (OWASP Dependency Check, SonarQube, Snyk)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
           path: backend/node_modules
           key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
           restore-keys: |
             ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci
        working-directory: backend

      # - name: Set up Java 17
      #   uses: actions/setup-java@v4
      #   with:
      #     distribution: 'temurin'
      #     java-version: '17'
      #     overwrite-settings: false

      - name: Install OWASP Dependency-Check
        run: |
          curl -L https://github.com/jeremylong/DependencyCheck/releases/download/v11.1.0/dependency-check-11.1.0-release.zip -o dependency-check-11.1.0-release.zip
          unzip dependency-check-11.1.0-release.zip -d dependency-check
          chmod +x dependency-check/dependency-check
        working-directory: backend

      - name: Run OWASP Dependency Check
        run: |
          dependency-check/dependency-check/bin/dependency-check.sh --project "Role Mapper" --scan . --nvdApiKey ${{ secrets.NVD_API_KEY }} --format "HTML" --out dependency-check-report
        working-directory: backend

      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-check-report
          path: ./backend/dependency-check-report/*.html


      # - name: Authenticate with Snyk
      #   run: npm run snyk:auth ${{ secrets.SNYK_TOKEN }}
      #   working-directory: backend

      # - name: Run Snyk Test
      #   run: snyk test
      #   working-directory: backend

      # - name: Upload Snyk Report
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: snyk-report
      #     path: backend/snyk-results.json

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USER }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Run Docker Scout CVE Scan
      #   run: docker scout cves --format markdown -o docker-cve-report.md calebscript/role-mapper:2024.12.1

      # - name: Upload Docker Scout CVE Report
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: docker-scout-cve-report
      #     path: docker-cve-report.json

      # - name: Run Docker Scout Quickview
      #   run: docker scout quickview -o docker-quickview-report.txt calebscript/role-mapper:2024.12.1

      # - name: Upload Docker Scout Quickview Report
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: docker-scout-quickview-report
      #     path: docker-quickview-report.txt

      # - name: SonarQube Scan
      #   uses: sonarsource/sonarcloud-github-action@v1
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   with:
      #     args: >
      #       -Dsonar.projectKey=roleMapper
      #       -Dsonar.organization=h-ka.de
      #       -Dsonar.host.url=https://sonarcloud.io
      #       -Dsonar.sources=./backend
