name: Security Pipeline
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  security:
    name: Security Scans (OWASP Dependency Check, SonarQube, Snyk)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
           path: node_modules
           key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
           restore-keys: |
             ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci
        working-directory: backend

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Run OWASP Dependency Check (Docker)
        run: |
          docker run -d --rm \
          -v $(pwd):/src \
          -v $(pwd)/dc-report:/report \
          owasp/dependency-check:latest \
          --project "Bankkonto" \
          --scan /src \
          --format "HTML" \
          --out /report \
          --nvdApiKey ${{ secrets.NVD_API_KEY }}

      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-check-report
          path: ./backend/dc-report/*.html

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: "-Dsonar.projectKey=roleMapper -Dsonar.organization=h-ka.de"

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Test
        run: snyk test backend

      - name: Upload Snyk Report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: backend/snyk-results.json

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Docker Scout CVE Scan
        run: docker scout cves --format json calebscript/role-mapper:2024.12.1

      - name: Run Docker Scout Quickview
        run: docker scout quickview --format json calebscript/role-mapper:2024.12.1
