name: Test Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      TEST_MONGODB_DATABASE: ${{ secrets.TEST_MONGODB_DATABASE }}

    steps:
    - name: Print ref name
      run: echo "This workflow was triggered by ${{ github.ref_name }}

    - name: Print actor (Collaborator)
      run: echo "The actor is ${{ github.actor }}"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm install
      working-directory: backend

    - name: Run ESLint
      run: npm run eslint
      working-directory: backend

    - name: Run tests
      run: npm t
      working-directory: backend

    - name: Run Coverage Tests with Istanbul
      run: npm run test:istanbul
      working-directory: backend

    - name: Upload Jest Test Coverage
      uses: actions/upload-artifact@v4
      with:
        name: jest-coverage
        path: ./backend/coverage

    - name: Audit dependencies
      run: npm audit --audit-level=high
      working-directory: backend
