name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm install
      working-directory: backend

    - name: Run ESLint
      run: npm run eslint
      working-directory: backend

    - name: Run tests
      run: npm t
      working-directory: backend

    - name: Audit dependencies
      run: npm audit --audit-level=high
      working-directory: backend

    - name: Save test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: backend/test-results/

