name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: go to backend directory
      run: cd backend

    - name:  ls -al
      run: ls -al

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
